# Made by FluffyNarwhals

money:
  rename-price: 20.0
  # If this is true, the pet-price below will be the same price for all pets. If it is false, pet-price won't be used
  single-pet-price: true
  pet-price: 500.0
options:
  # If this is true, the pet will be invincible WHILE IN PASSIVE MODE!
  # In aggressive mode, the pet can be killed no matter what
  # because it is attacking stuff.
  invincible: true
  ride-pets: true
  tame-pets: true